#!/usr/bin/env python3
"""Turns a TrueType font into a black and white bitmap font for gfx.c.

    python tools/make_font.py FONT.ttf CAP_HEIGHT NAME > main/NAME.c

CAP_HEIGHT is the height of the capital letters in pixels; the font is
rendered at the size that gives it. Glyphs are rendered without
anti-aliasing (the e-paper is black and white), with the font's hinting,
for ASCII 0x20..0x7E. Needs Pillow (pip install pillow).
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont, ImageOps

FIRST, LAST = 0x20, 0x7E


def font_for_cap(path, cap):
    for size in range(6, 100):
        font = ImageFont.truetype(path, size)
        if -font.getbbox('H', anchor='ls')[1] >= cap:
            return font
    sys.exit(f'No size gives capitals {cap} pixels tall')


def render(font, ch):
    """The glyph's pixels, where they sit against the pen position on the
    baseline, and how far the pen moves on"""
    size = font.size * 3
    img = Image.new('1', (size, size), 1)
    draw = ImageDraw.Draw(img)
    draw.fontmode = '1'
    origin = (font.size, font.size * 2)
    draw.text(origin, ch, font=font, anchor='ls', fill=0)
    advance = round(font.getlength(ch))
    box = ImageOps.invert(img.convert('L')).getbbox()
    if not box:
        return [], 0, 0, 0, 0, advance
    left, top, right, bottom = box
    rows = [[img.getpixel((x, y)) == 0 for x in range(left, right)] for y in range(top, bottom)]
    return rows, right - left, bottom - top, left - origin[0], top - origin[1], advance


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    path, cap, name = sys.argv[1], int(sys.argv[2]), sys.argv[3]
    font = font_for_cap(path, cap)

    bitmap, glyphs = [], []
    for code in range(FIRST, LAST + 1):
        rows, w, h, x_off, y_off, advance = render(font, chr(code))
        # Rows one after another, packed 8 pixels a byte, MSB first
        bits = [b for row in rows for b in row]
        offset = len(bitmap)
        for i in range(0, len(bits), 8):
            byte = 0
            for j, bit in enumerate(bits[i:i + 8]):
                byte |= bit << (7 - j)
            bitmap.append(byte)
        glyphs.append((offset, w, h, advance, x_off, y_off, chr(code)))

    ascent, descent = font.getmetrics()
    family, style = font.getname()
    out = [
        f'// {family} {style}, capitals {cap} pixels tall ({font.size} px font size), black and',
        f'// white. Generated by tools/make_font.py from {os.path.basename(path)}: don\'t edit.',
        '// DejaVu fonts licence (Bitstream Vera): see LICENSES/DejaVu.txt.' if 'DejaVu' in family else None,
        '#include "gfx.h"',
        '',
        f'static const uint8_t {name}_bitmap[] = {{',
    ]
    for i in range(0, len(bitmap), 16):
        out.append('    ' + ', '.join(f'0x{b:02X}' for b in bitmap[i:i + 16]) + ',')
    out += ['};', '', f'static const gfx_glyph_t {name}_glyphs[] = {{']
    for offset, w, h, advance, x_off, y_off, ch in glyphs:
        shown = {' ': 'space', '\\': 'backslash', "'": 'quote'}.get(ch, ch)
        out.append(f'    {{{offset}, {w}, {h}, {advance}, {x_off}, {y_off}}}, // {shown}')
    out += [
        '};',
        '',
        f'const gfx_font_t {name} = {{',
        f'    .bitmap = {name}_bitmap,',
        f'    .glyphs = {name}_glyphs,',
        f'    .first = 0x{FIRST:02X},',
        f'    .last = 0x{LAST:02X},',
        f'    .cap_height = {cap},',
        f'    .descent = {descent},',
        '};',
    ]
    print('\n'.join(line for line in out if line is not None))


if __name__ == '__main__':
    main()
